version: '3.9'

services:
    web:
        build:
            context: ..
            dockerfile: ./Docker/web.dev.Dockerfile
        command: python3 manage.py runserver 0.0.0.0:8000
        ports:
            - "8000:8000"
        volumes:
            - ../src:/home/app/web
